eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  host:   
    socket-timeout-millis: 60000  
    connect-timeout-millis: 60000
  routes:
    rib:
      path: /api-a/**
      serviceId: service-ribbon
    fei:
      path: /api-b/**
      serviceId: service-feign
ribbon:   
  ReadTimeout: 60000
  ConnectTimeout: 60000         #跟下面的时间哪个短，哪个生效
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000