server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: C:/config/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/